### ISSUE TITLE
Cannot import files accurately

### ISSUE THREAD

**Issue by fengtingle615** [WenjieDu/TSDB#33]
### Issue description

Traceback (most recent call last):
  File "D:\代码  好用\SAITS-main\dataset_generating_scripts\gene_PhysioNet2012_dataset.py", line 36, in <module>
    from tsdb import pickle_dump
ImportError: cannot import name 'pickle_dump' from 'tsdb' (D:\anaconda\envs\pytorch\lib\site-packages\tsdb\__init__.py)
'NoneType' object has no attribute 'split'

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to TSDB! You can follow me on GitHub to receive the latest news of TSDB. If you find TSDB helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice TSDB. It matters and is definitely a kind of contribution to the PyPOTS community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
In private conversation, @fengtingle615 solved this problem by recreating a new conda environment. So this is not an error in TSDB.
