### ISSUE TITLE
您好，请问此库可以自行添加自己想用的数据集以供使用吗

### ISSUE THREAD

**Issue by HANSZJH** [WenjieDu/TSDB#63]
### Issue description

谢谢

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to TSDB and PyPOTS! You can follow me on GitHub to receive the latest news of TSDB and PyPOTS. If you find TSDB helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie
